version: '3'
services:
  php:
    build: docker/php/
    container_name: api_php
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: api_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/

  mysql:
    image: mariadb:latest
    container_name: api_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456